### ISSUE TITLE
How to co-simulate with ICEPAK?

### ISSUE THREAD

**Issue by Brilight** [ansys/pyseascape#135]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

hi there, thanks for your contribution on the package!

Recently, I am engaged in simulating the advanced package system with ANSYS, including RedHawk and Icepak in my python env. So I am curious about how to co-simulate these two tools. Could you please provide with an example or some illustrations?

### 📝 Steps to reproduce

None

### 💻 Which operating system are you using?

Linux

### 📀 Which ANSYS version are you using?

ANSYS AEDT Student version 23.2
RedHawk 2023

### 🐍 Which Python version are you using?

3.9

### 📦 Installed packages

```shell
Pyaedt
PySeascape 
and other required
```

**Comment by RobPasMue** [comment]
Pinging @kaleabhip for visibilitity

**Comment by kaleabhip** [comment]
@Brilight I talked with the internal teams. Currently, there are no co-simulation capabilities between AEDT and Redhawk. 
Also, there are multiple products in the Redhawk group including RedHawk, RedHawk-SC, RedHawk-SC ET, and so on. PySeaScape  specifically connects to RedHawk-SC backend. Can you please specify what is the exact simulation/scenario that you are working with? I can help you better help you with what solutions we have.

**Comment by Brilight** [comment]
> @Brilight I talked with the internal teams. Currently, there are no co-simulation capabilities between AEDT and Redhawk. Also, there are multiple products in the Redhawk group including RedHawk, RedHawk-SC, RedHawk-SC ET, and so on. PySeaScape specifically connects to RedHawk-SC backend. Can you please specify what is the exact simulation/scenario that you are working with? I can help you better help you with what solutions we have.

Thanks for your kind reply~ Actually, I am working on the power-thermal co-simulation of 3DIC. So I want to try the co-simulation flow composed of ICEPAK and RedHawk SC ET,  an interesting feature announced last year. Since I also want to optimize the 3DIC structure with python scripts, so i open the issue to look up for methods for the co-simulation of icepak and redhawk sc et in python env. Again, thanks for your help~

**Comment by lorenzovecchietti** [comment]
Hi @Brilight,

you want to apply to your RH-SC ET simulation HTC boundary conditions from Icepak, right?
![immagine](https://github.com/ansys/pyseascape/assets/58366962/bfe8e398-4c34-4a2f-9d95-957f7f2af9e6)

For the pyAEDT side, once you simulation is done, you can just use [this function](https://aedt.docs.pyansys.com/version/0.9/API/_autosummary/pyaedt.modules.AdvancedPostProcessing.PostProcessor.export_field_file.html#pyaedt.modules.AdvancedPostProcessing.PostProcessor.export_field_file) to save the file with the HTC boundary condition you'll want to use in RH-SC ET.

So the relevant part of the code will be something like this:
```
import pyaedt

ipk=pyaedt.Icepak()
# code to setup and solve simulation
output_file = "C:\\test.fld"
ipk.post.export_field_file(quantity="Heat_Transfer_Coeff", objects_type="Surf", assignment="AllObjects", output_dir=output_file )
```

Let's see if someone is able to help on the pyseascape side, else I'll try to have a look next week.
Hope this helps :)

**Comment by kaleabhip** [comment]
@Brilight Is your issue resolved? If so, I will mark this as closed.

**Comment by kaleabhip** [comment]
No update. Closing this issue. Please reopen if needed
